
version: '3'

services:
  deep_notebook:
    image: jupyter/tensorflow-notebook   
    volumes:
      - ./airflow/dags/:./airflow/dags/
    tty: true
    privileged: true
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_HOME=/spark
      - ENABLE_INIT_DAEMON='false'
    command:  start.sh jupyter lab --LabApp.token='' -e NB_UID=1000 --NotebookApp.notebook_dir=./airflow/dags/
    ports:
      - 8080:8888


  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432

  redis:
    image: 'redis:3.2.7'
    container_name: redis

  airflow:
     image: puckel/docker-airflow:1.9.0-2
     restart: always
     depends_on:
         - postgres
     environment:
         - LOAD_EX=n
         - EXECUTOR=Local
         - FERNET_KEY=my-local-fernet-key
     volumes:
         - ./airflow/dags:/usr/local/airflow/dags
         # custom plugins
         - ./airflow/plugins:/usr/local/airflow/plugins
     ports:
         - "8081:8080"
     command: webserver

  superset:
    image: amancevice/superset
    depends_on:
      - redis
    container_name: devtrac_superset
    ports:
      - "8088:8088"
    
networks:
  hadoop:
    external: true
